services:
  postgres:
    image: postgres:18.1-trixie
    container_name: trinity-postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      trinity-net:
        ipv4_address: 172.20.0.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  migrate:
    image: migrate/migrate:v4.19.1
    container_name: migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./internal/user/infrastructure/migrations:/migrations
    command: -path=/migrations -database=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}?sslmode=disable up
    networks:
      trinity-net:
        ipv4_address: 172.20.0.3
    healthcheck:
      test: ["CMD", "test", "-f", "/migrations/.migrate-completed"]
      interval: 5s
      timeout: 5s
      retries: 0

  redis:
    image: redis:8.4-bookworm
    container_name: trinity-redis
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD} --bind 172.20.0.4
    networks:
      trinity-net:
        ipv4_address: 172.20.0.4
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "-h", "172.20.0.4", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 10s
      timeout: 5s
      retries: 3

  trinity:
    build: .
    container_name: trinity-app
    environment:
      DATABASE_ADDRESS: ${DATABASE_ADDRESS}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL_MODE: ${DATABASE_SSL_MODE}
      REDIS_ADDRESS: ${REDIS_ADDRESS}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB_AUTH: ${REDIS_DB_AUTH}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      SERVER_ENVIRONMENT: ${SERVER_ENVIRONMENT}
      SERVER_ADDRESS: ${SERVER_ADDRESS}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_TRUSTED_PROXY: ${SERVER_TRUSTED_PROXY}
      SERVER_ALLOWED_ORIGIN: ${SERVER_ALLOWED_ORIGIN}
    ports:
      - "8080:8080"
      - "6060:6060"
    networks:
      trinity-net:
        ipv4_address: 172.20.0.5
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: "service_completed_successfully"

networks:
  trinity-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
  redis_data: